export const kpiStats = [
  {
    id: 'total-customers',
    title: 'Total Customers',
    value: '2,458',
    change: '+12.5%',
    isPositive: true,
    subtitle: 'vs last 30 days',
    icon: 'Users',
    color: 'emerald',
  },
  {
    id: 'active-policies',
    title: 'Active Policies',
    value: '5,783',
    change: '+8.3%',
    isPositive: true,
    subtitle: 'vs last 30 days',
    icon: 'ShieldCheck',
    color: 'blue',
  },
  {
    id: 'total-claims',
    title: 'Total Claims',
    value: '1,246',
    change: '-4.2%',
    isPositive: false,
    subtitle: 'vs last 30 days',
    icon: 'FileText',
    color: 'purple',
  },
  {
    id: 'premium-collected',
    title: 'Premium Collected',
    value: '$2,45,850',
    change: '+15.6%',
    isPositive: true,
    subtitle: 'vs last 30 days',
    icon: 'DollarSign',
    color: 'amber',
  },
  {
    id: 'pending-claims',
    title: 'Pending Claims',
    value: '234',
    change: '+3.6%',
    isPositive: false,
    subtitle: 'vs last 30 days',
    icon: 'Hourglass',
    color: 'rose',
  },
  {
    id: 'expiring-policies',
    title: 'Expiring Policies',
    value: '726',
    change: '12.6%',
    isPositive: false,
    subtitle: 'next 30 days',
    icon: 'AlertTriangle',
    color: 'orange',
  },
];

export const monthlyRevenueData = [
  { month: 'Jan', revenue: 30000, target: 28000 },
  { month: 'Feb', revenue: 32000, target: 30000 },
  { month: 'Mar', revenue: 42000, target: 35000 },
  { month: 'Apr', revenue: 40000, target: 38000 },
  { month: 'May', revenue: 52000, target: 45000 },
  { month: 'Jun', revenue: 48000, target: 46000 },
];

export const claimsOverviewData = [
  { name: 'Approved', value: 568, percentage: '45.6%', color: '#10B981' },
  { name: 'Pending', value: 234, percentage: '18.8%', color: '#F59E0B' },
  { name: 'In Review', value: 278, percentage: '22.3%', color: '#3B82F6' },
  { name: 'Rejected', value: 166, percentage: '13.3%', color: '#EF4444' },
];

export const topPolicyTypes = [
  { name: 'Health Insurance', percentage: 35, count: '2,024', color: '#10B981' },
  { name: 'Life Insurance', percentage: 28, count: '1,619', color: '#6366F1' },
  { name: 'Vehicle Insurance', percentage: 20, count: '1,156', color: '#3B82F6' },
  { name: 'Home Insurance', percentage: 17, count: '984', color: '#F59E0B' },
];

export const customerGrowthData = [
  { month: 'Jan', customers: 1200 },
  { month: 'Feb', customers: 1550 },
  { month: 'Mar', customers: 1900 },
  { month: 'Apr', customers: 2150 },
  { month: 'May', customers: 2320 },
  { month: 'Jun', customers: 2458 },
];

export const claimsByCategoryData = [
  { name: 'Health', value: 48, color: '#10B981' },
  { name: 'Vehicle', value: 26, color: '#3B82F6' },
  { name: 'Life', value: 16, color: '#F59E0B' },
  { name: 'Other', value: 10, color: '#8B5CF6' },
];

export const recentClaimsData = [
  {
    id: 'CLM-2025-1256',
    policyNumber: 'POL-2025-089',
    customer: {
      name: 'John Smith',
      email: 'john.smith@gmail.com',
      avatar: 'https://i.pravatar.cc/150?u=johnsmith',
    },
    claimAmount: '$5,250',
    status: 'In Review',
    submittedOn: 'Jun 12, 2025',
    priority: 'High',
    type: 'Health Insurance',
  },
  {
    id: 'CLM-2025-1255',
    policyNumber: 'POL-2025-088',
    customer: {
      name: 'Sarah Johnson',
      email: 'sarah.j@outlook.com',
      avatar: 'https://i.pravatar.cc/150?u=sarahj',
    },
    claimAmount: '$3,750',
    status: 'Pending',
    submittedOn: 'Jun 11, 2025',
    priority: 'Medium',
    type: 'Vehicle Insurance',
  },
  {
    id: 'CLM-2025-1254',
    policyNumber: 'POL-2025-087',
    customer: {
      name: 'Michael Brown',
      email: 'm.brown@techcorp.io',
      avatar: 'https://i.pravatar.cc/150?u=mbrown',
    },
    claimAmount: '$8,900',
    status: 'Approved',
    submittedOn: 'Jun 10, 2025',
    priority: 'High',
    type: 'Home Insurance',
  },
  {
    id: 'CLM-2025-1253',
    policyNumber: 'POL-2025-086',
    customer: {
      name: 'Emily Davis',
      email: 'emily.davis@design.co',
      avatar: 'https://i.pravatar.cc/150?u=emilyd',
    },
    claimAmount: '$2,180',
    status: 'Rejected',
    submittedOn: 'Jun 10, 2025',
    priority: 'Low',
    type: 'Health Insurance',
  },
  {
    id: 'CLM-2025-1252',
    policyNumber: 'POL-2025-085',
    customer: {
      name: 'David Wilson',
      email: 'david.w@fintech.org',
      avatar: 'https://i.pravatar.cc/150?u=davidw',
    },
    claimAmount: '$4,600',
    status: 'In Review',
    submittedOn: 'Jun 09, 2025',
    priority: 'Medium',
    type: 'Vehicle Insurance',
  },
];

export const policyStatusDistribution = [
  { label: 'Active Policies', count: 4215, percentage: '72.8%', color: '#10B981' },
  { label: 'Expired Policies', count: 842, percentage: '14.6%', color: '#EF4444' },
  { label: 'Expiring Soon (30 Days)', count: 726, percentage: '12.6%', color: '#F59E0B' },
];

export const recentNotificationsData = [
  {
    id: 'notif-1',
    title: 'Policy Expiry Alert',
    message: 'Policy CLM-2025-001 is expiring in 15 days.',
    time: '2 min ago',
    type: 'warning',
    read: false,
  },
  {
    id: 'notif-2',
    title: 'New Claim Submission',
    message: 'New claim CLM-2025-1256 submitted by John Smith.',
    time: '15 min ago',
    type: 'info',
    read: false,
  },
  {
    id: 'notif-3',
    title: 'Payment Received',
    message: 'Payment of $1,250 received for policy POL-2025-089.',
    time: '30 min ago',
    type: 'success',
    read: true,
  },
  {
    id: 'notif-4',
    title: 'Review Required',
    message: 'Claim CLM-2025-1245 requires urgent manager review.',
    time: '1 hour ago',
    type: 'error',
    read: true,
  },
];

export const customersList = [
  {
    id: 'CUST-8041',
    name: 'John Smith',
    email: 'john.smith@gmail.com',
    phone: '+1 (555) 234-5678',
    avatar: 'https://i.pravatar.cc/150?u=johnsmith',
    city: 'New York, USA',
    status: 'Active',
    tier: 'Platinum',
    policiesCount: 3,
    totalPremiums: '$14,200',
    joinedDate: 'Jan 15, 2023',
    riskScore: 'Low (98/100)',
  },
  {
    id: 'CUST-8042',
    name: 'Sarah Johnson',
    email: 'sarah.j@outlook.com',
    phone: '+1 (555) 876-5432',
    avatar: 'https://i.pravatar.cc/150?u=sarahj',
    city: 'San Francisco, USA',
    status: 'Active',
    tier: 'Gold',
    policiesCount: 2,
    totalPremiums: '$9,800',
    joinedDate: 'Mar 22, 2023',
    riskScore: 'Medium (82/100)',
  },
  {
    id: 'CUST-8043',
    name: 'Michael Brown',
    email: 'm.brown@techcorp.io',
    phone: '+1 (555) 345-6789',
    avatar: 'https://i.pravatar.cc/150?u=mbrown',
    city: 'Chicago, USA',
    status: 'Active',
    tier: 'Enterprise',
    policiesCount: 5,
    totalPremiums: '$34,500',
    joinedDate: 'Nov 04, 2022',
    riskScore: 'Low (95/100)',
  },
  {
    id: 'CUST-8044',
    name: 'Emily Davis',
    email: 'emily.davis@design.co',
    phone: '+1 (555) 901-2345',
    avatar: 'https://i.pravatar.cc/150?u=emilyd',
    city: 'Seattle, USA',
    status: 'Pending',
    tier: 'Silver',
    policiesCount: 1,
    totalPremiums: '$3,200',
    joinedDate: 'May 10, 2024',
    riskScore: 'Low (91/100)',
  },
  {
    id: 'CUST-8045',
    name: 'David Wilson',
    email: 'david.w@fintech.org',
    phone: '+1 (555) 456-7890',
    avatar: 'https://i.pravatar.cc/150?u=davidw',
    city: 'Austin, USA',
    status: 'Active',
    tier: 'Gold',
    policiesCount: 2,
    totalPremiums: '$11,400',
    joinedDate: 'Aug 19, 2023',
    riskScore: 'Medium (78/100)',
  },
  {
    id: 'CUST-8046',
    name: 'Jessica Taylor',
    email: 'jessica.t@global.com',
    phone: '+1 (555) 678-9012',
    avatar: 'https://i.pravatar.cc/150?u=jessicat',
    city: 'Boston, USA',
    status: 'Inactive',
    tier: 'Silver',
    policiesCount: 1,
    totalPremiums: '$4,100',
    joinedDate: 'Feb 01, 2024',
    riskScore: 'High (64/100)',
  },
];

export const policiesList = [
  {
    id: 'POL-2025-089',
    holder: 'John Smith',
    holderAvatar: 'https://i.pravatar.cc/150?u=johnsmith',
    type: 'Health Insurance',
    planName: 'Comprehensive Executive Health',
    premium: '$450 / month',
    coverage: '$1,000,000',
    startDate: 'Jan 01, 2025',
    endDate: 'Dec 31, 2025',
    status: 'Active',
    agent: 'Alex Johnson',
  },
  {
    id: 'POL-2025-088',
    holder: 'Sarah Johnson',
    holderAvatar: 'https://i.pravatar.cc/150?u=sarahj',
    type: 'Vehicle Insurance',
    planName: 'Full Comprehensive Auto Care',
    premium: '$280 / month',
    coverage: '$150,000',
    startDate: 'Feb 15, 2025',
    endDate: 'Feb 14, 2026',
    status: 'Active',
    agent: 'Marcus Vance',
  },
  {
    id: 'POL-2025-087',
    holder: 'Michael Brown',
    holderAvatar: 'https://i.pravatar.cc/150?u=mbrown',
    type: 'Home Insurance',
    planName: 'Luxury Property & Structural Shield',
    premium: '$820 / month',
    coverage: '$2,500,000',
    startDate: 'Mar 10, 2025',
    endDate: 'Mar 09, 2026',
    status: 'Active',
    agent: 'Sophia Lin',
  },
  {
    id: 'POL-2025-086',
    holder: 'Emily Davis',
    holderAvatar: 'https://i.pravatar.cc/150?u=emilyd',
    type: 'Life Insurance',
    planName: 'Term Life Select Preferred',
    premium: '$190 / month',
    coverage: '$500,000',
    startDate: 'Jul 01, 2024',
    endDate: 'Jun 30, 2025',
    status: 'Expiring Soon',
    agent: 'Alex Johnson',
  },
  {
    id: 'POL-2025-085',
    holder: 'David Wilson',
    holderAvatar: 'https://i.pravatar.cc/150?u=davidw',
    type: 'Vehicle Insurance',
    planName: 'Commercial Fleet Basic',
    premium: '$350 / month',
    coverage: '$250,000',
    startDate: 'Jan 10, 2024',
    endDate: 'Jan 09, 2025',
    status: 'Expired',
    agent: 'Marcus Vance',
  },
];

export const premiumsList = [
  {
    invoiceId: 'INV-9021',
    policyNumber: 'POL-2025-089',
    customer: 'John Smith',
    amount: '$1,250.00',
    paymentMethod: 'Credit Card (Visa •••• 4242)',
    dueDate: 'Jun 15, 2025',
    paidDate: 'Jun 12, 2025',
    status: 'Paid',
  },
  {
    invoiceId: 'INV-9022',
    policyNumber: 'POL-2025-088',
    customer: 'Sarah Johnson',
    amount: '$840.00',
    paymentMethod: 'ACH Direct Debit',
    dueDate: 'Jun 20, 2025',
    paidDate: 'Pending',
    status: 'Due Soon',
  },
  {
    invoiceId: 'INV-9023',
    policyNumber: 'POL-2025-087',
    customer: 'Michael Brown',
    amount: '$2,460.00',
    paymentMethod: 'Wire Transfer',
    dueDate: 'Jun 05, 2025',
    paidDate: '-',
    status: 'Overdue',
  },
  {
    invoiceId: 'INV-9024',
    policyNumber: 'POL-2025-086',
    customer: 'Emily Davis',
    amount: '$570.00',
    paymentMethod: 'Credit Card (Mastercard •••• 8821)',
    dueDate: 'Jun 01, 2025',
    paidDate: 'May 29, 2025',
    status: 'Paid',
  },
];

export const documentsList = [
  {
    id: 'DOC-101',
    name: 'Medical_Checkup_Report_JohnSmith.pdf',
    category: 'Medical Reports',
    size: '2.4 MB',
    uploadedOn: 'Jun 10, 2025',
    uploadedBy: 'John Smith',
    status: 'Verified',
  },
  {
    id: 'DOC-102',
    name: 'Vehicle_Damage_Photos_SarahJ.zip',
    category: 'Claim Proofs',
    size: '14.8 MB',
    uploadedOn: 'Jun 11, 2025',
    uploadedBy: 'Sarah Johnson',
    status: 'Pending Verification',
  },
  {
    id: 'DOC-103',
    name: 'Home_Property_Title_Deed.pdf',
    category: 'Policy Agreements',
    size: '5.1 MB',
    uploadedOn: 'Mar 10, 2025',
    uploadedBy: 'Michael Brown',
    status: 'Verified',
  },
  {
    id: 'DOC-104',
    name: 'National_ID_Card_EmilyDavis.jpg',
    category: 'Identification',
    size: '850 KB',
    uploadedOn: 'May 10, 2024',
    uploadedBy: 'Emily Davis',
    status: 'Verified',
  },
];

export const agentsList = [
  {
    id: 'AGT-01',
    name: 'Alex Johnson',
    role: 'Senior Underwriter & Administrator',
    email: 'alex.j@insurepro.com',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=200',
    assignedCustomers: 142,
    activePolicies: 310,
    claimResolutionRate: '98.4%',
    revenueGenerated: '$420,000',
    status: 'Active',
  },
  {
    id: 'AGT-02',
    name: 'Marcus Vance',
    role: 'Claims Specialist Lead',
    email: 'marcus.v@insurepro.com',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=200',
    assignedCustomers: 98,
    activePolicies: 215,
    claimResolutionRate: '96.1%',
    revenueGenerated: '$290,000',
    status: 'Active',
  },
  {
    id: 'AGT-03',
    name: 'Sophia Lin',
    role: 'Enterprise Account Manager',
    email: 'sophia.l@insurepro.com',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=200',
    assignedCustomers: 185,
    activePolicies: 450,
    claimResolutionRate: '99.2%',
    revenueGenerated: '$780,000',
    status: 'Active',
  },
];

export const auditLogsList = [
  {
    id: 'LOG-8801',
    user: 'Alex Johnson',
    role: 'Admin',
    action: 'APPROVED_CLAIM',
    details: 'Approved claim CLM-2025-1254 for $8,900',
    ip: '192.168.1.42',
    timestamp: 'Jun 12, 2025 - 14:32:05',
    category: 'Claims',
  },
  {
    id: 'LOG-8802',
    user: 'Marcus Vance',
    role: 'Agent',
    action: 'RECORDED_PAYMENT',
    details: 'Recorded payment of $1,250 for invoice INV-9021',
    ip: '192.168.1.88',
    timestamp: 'Jun 12, 2025 - 12:15:40',
    category: 'Financial',
  },
  {
    id: 'LOG-8803',
    user: 'Sophia Lin',
    role: 'Agent',
    action: 'CREATED_POLICY',
    details: 'Created new policy POL-2025-089 for John Smith',
    ip: '192.168.1.19',
    timestamp: 'Jun 11, 2025 - 09:45:12',
    category: 'Policies',
  },
  {
    id: 'LOG-8804',
    user: 'System Admin',
    role: 'System',
    action: 'SECURITY_BACKUP',
    details: 'Automated database and encrypted audit log backup completed',
    ip: '127.0.0.1',
    timestamp: 'Jun 11, 2025 - 02:00:00',
    category: 'System',
  },
];
